const {
  PORT: port = 3000
} = process.env

export const PORT = +port

export {
  GRAPH_NAME,
  REDIS_HOST,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  PRIVATE_KEY,
  PUBLIC_KEY,
  COOKIE_SAMESITE,
  COOKIE_PATH,
  COOKIE_SECURE,
  COOKIE_DOMAIN,
  S3_ENDPOINT,
  S3_ACCESS_KEY,
  S3_SECRET_KEY,
  ALLOW_SHOOTING_CREATION
}
